### ISSUE TITLE
Review Drake modules

### ISSUE THREAD

**Issue by OnofreTZK** [OnofreTZK/Sheldrake#16]
# Tasks
- [x] Dispose `Mempool` and `Chain`\
- [x] Rewrite `Transaction` and `Block` to adapt to `t list`
- [x] Genesis block at first migration

**Comment by OnofreTZK** [comment]
# Avoid mutable fields on `Block.t`
ref: https://github.com/OnofreTZK/MoreOCaml/blob/main/NamedTuplesAndRecords/named_tuples_and_records.ml
